// Activity log — 野と形
// Entries extracted from meeting minutes 2026-03-17, 2026-04-01, 2026-04-14
// Categories: session(対話) / concept(コンセプト) / research(リサーチ) / fieldwork(フィールドワーク) / task(宿題)

window.NTK_ENTRIES = [
  {
    id: "2026-03-17-session",
    date: "2026-03-17",
    dateLabel: { y: "2026", m: "03", d: "17" },
    month: "March",
    category: "session",
    categoryLabel: "対話",
    categoryEn: "Session",
    title: "ユニット立ち上げ、方向性の擦り合わせ",
    titleEn: "Kick-off — Aligning Direction",
    summary:
      "リサーチャー村上とデザイナー松井の二人による、共同プロジェクト立ち上げに向けた最初の本格的な対話。イベント出展の現実性、参照スタジオのポジショニング、民芸・工芸の系譜、そして「役に立つではなく、意味がある」というコンセプトの萌芽まで、議論は多岐にわたった。",
    threads: ["unit", "position", "concept"],
    duration: null,
  },
  {
    id: "2026-03-17-position",
    date: "2026-03-17",
    dateLabel: { y: "2026", m: "03", d: "17" },
    month: "March",
    category: "concept",
    categoryLabel: "コンセプト",
    categoryEn: "Concept",
    title: "参照スタジオと自分たちのポジション",
    titleEn: "Reference Studios & Our Position",
    summary:
      "フォルマファンタズマ、スタジオスワイン、UMAデザイン、Wii Plus を参照しながら、村上作成の2軸マッピング（商業的↔インディペンデント／試作的↔実用的）で自分たちの立ち位置を「インディペンデント × 実用的」象限に置く。スペキュラティブな試作性も併せ持つ独特のゾーン。",
    threads: ["position"],
  },
  {
    id: "2026-03-17-mingei",
    date: "2026-03-17",
    dateLabel: { y: "2026", m: "03", d: "17" },
    month: "March",
    category: "research",
    categoryLabel: "リサーチ",
    categoryEn: "Research",
    title: "民芸・工芸の系譜を辿る",
    titleEn: "Tracing the Mingei Lineage",
    summary:
      "柳宗悦・柳宗理の流れを村上が図書館で独自勉強中。「工芸とプロダクトデザインの両方をちゃんと見てものを作る」姿勢。日用品であること、作品しすぎないこと。農民芸術の痕跡、ムサビの民族資料室、宮本常一の系譜にも関心が広がる。",
    threads: ["mingei", "concept"],
  },
  {
    id: "2026-03-17-carpet",
    date: "2026-03-17",
    dateLabel: { y: "2026", m: "03", d: "17" },
    month: "March",
    category: "concept",
    categoryLabel: "コンセプト",
    categoryEn: "Concept",
    title: "「役に立つではなく、意味がある。でも使える」",
    titleEn: "Not Useful, but Meaningful — Yet Usable",
    summary:
      "松井が絨毯屋で見たヴィンテージのペルシャ絨毯。イスラム教徒の老人が長年お祈りに使い、膝をついた形にへこんでいた。柄に宗教的・文化的な意味が込められ、「使いやすい」ではなく「意味がある」ものとして機能している。ユニットの核となるコンセプトが、この一枚の絨毯から浮上した。",
    threads: ["concept"],
    quote: "役に立つではなく、意味がある。でも使える。",
  },
  {
    id: "2026-03-17-hamamatsu",
    date: "2026-03-17",
    dateLabel: { y: "2026", m: "03", d: "17" },
    month: "March",
    category: "research",
    categoryLabel: "リサーチ",
    categoryEn: "Research",
    title: "浜松ならではの切り口",
    titleEn: "Hamamatsu as a Field",
    summary:
      "ブラジル・フィリピン・ベトナム系など多国籍移民コミュニティ。本田・ヤマハ・スズキ・河合楽器等の工場労働に根づく儀礼的な習慣（ラジオ体操など）。浜松まつり（凧揚げ）の独特なコミュニティ構造。遠州織物の歴史。企業城下町として層が分断された、独特の場所。",
    threads: ["hamamatsu"],
  },
  {
    id: "2026-03-17-events",
    date: "2026-03-17",
    dateLabel: { y: "2026", m: "03", d: "17" },
    month: "March",
    category: "task",
    categoryLabel: "行動",
    categoryEn: "Action",
    title: "イベント・出展先の検討",
    titleEn: "Events — Where to Show",
    summary:
      "東京アートブックフェア（12月）→ まず見学で合意。メーカーフェア → 方向性が合わず見送り。デザインタイド → 若手デザイナーの実験的な雰囲気が二人に合うと感触。共通の販売モデル：「展示して、売れるものを後から少量生産・オンライン販売」。",
    threads: ["exhibit"],
  },

  {
    id: "2026-04-01-session",
    date: "2026-04-01",
    dateLabel: { y: "2026", m: "04", d: "01" },
    month: "April",
    category: "session",
    categoryLabel: "対話",
    categoryEn: "Session",
    title: "テーマ探求・アイデア創出",
    titleEn: "Theme Exploration & Ideation",
    summary:
      "浜松の地域産業やものづくりの技術を起点に、「土地性（テロワール）」「遊び（用途の転用）」「民藝と日用品」といったコンセプトを深掘りするブレインストーミング。62分のセッションで、具体的なリサーチ活動を含む初期アクションプランが合意された。",
    threads: ["unit", "terroir", "play"],
    duration: "62分",
  },
  {
    id: "2026-04-01-terroir",
    date: "2026-04-01",
    dateLabel: { y: "2026", m: "04", d: "01" },
    month: "April",
    category: "concept",
    categoryLabel: "コンセプト",
    categoryEn: "Concept",
    title: "土地性（テロワール）を工業製品へ",
    titleEn: "Terroir, Applied to Industry",
    summary:
      "ワインの「テロワール」概念を工業製品に応用する。産地による品質の「不揃い」や個性を価値として捉える。デジタル化できない土の質のような、物理的・身体的な情報に価値があるのではないか。民藝と焼き物は、土地の土から作られる究極のテロワール製品として位置づけられた。",
    threads: ["terroir", "soil"],
  },
  {
    id: "2026-04-01-play",
    date: "2026-04-01",
    dateLabel: { y: "2026", m: "04", d: "01" },
    month: "April",
    category: "concept",
    categoryLabel: "コンセプト",
    categoryEn: "Concept",
    title: "遊びと用途の転用",
    titleEn: "Play & Repurposing",
    summary:
      "モノの本来の用途を意図的にずらすことで生まれる「遊び」の可能性。マルティーノ・ガンパー「100日で100脚の椅子」をブリコラージュの実践例として参照。用途が未定義な「おもちゃ」の創出──積み木や粘土のように、遊び方が固定されないもの。",
    threads: ["play"],
  },
  {
    id: "2026-04-01-process",
    date: "2026-04-01",
    dateLabel: { y: "2026", m: "04", d: "01" },
    month: "April",
    category: "concept",
    categoryLabel: "コンセプト",
    categoryEn: "Concept",
    title: "素材との相互作用としてのものづくり",
    titleEn: "Making as a Dialogue with Material",
    summary:
      "人間が一方的に作るのではなく、素材（土など）との相互作用の中で形が生まれる、予測不可能なプロセスへの関心。料理や陶芸のように、作り手と素材の関係性が流動的で、結果が完全にコントロールされないものづくりを志向する。",
    threads: ["soil", "process"],
  },
  {
    id: "2026-04-01-hamamatsu-industry",
    date: "2026-04-01",
    dateLabel: { y: "2026", m: "04", d: "01" },
    month: "April",
    category: "research",
    categoryLabel: "リサーチ",
    categoryEn: "Research",
    title: "浜松の地場産業リスト",
    titleEn: "Hamamatsu Local Industries",
    summary:
      "リサーチ対象として浜松の地場産業を洗い出す。繊維（細幅織物）、金属加工（ヘラ絞り）、楽器パーツ（リガチャー）、寄木細工。訪問と連携の可能性を探ることが合意された。",
    threads: ["hamamatsu", "fieldwork"],
  },
  {
    id: "2026-04-01-methods",
    date: "2026-04-01",
    dateLabel: { y: "2026", m: "04", d: "01" },
    month: "April",
    category: "task",
    categoryLabel: "行動",
    categoryEn: "Action",
    title: "リサーチ手法を具体化する",
    titleEn: "Shaping the Research Methods",
    summary:
      "企業見学、家庭内リサーチ（知人3人に依頼して「台所・食器棚」と「文房具」の写真を収集）、『Dollar Street』や『地球家族』を参考にした海外の生活リサーチ。インプットを増やす方針が共有された。",
    threads: ["method", "fieldwork"],
  },

  {
    id: "2026-04-14-session",
    date: "2026-04-14",
    dateLabel: { y: "2026", m: "04", d: "14" },
    month: "April",
    category: "session",
    categoryLabel: "対話",
    categoryEn: "Session",
    title: "リサーチ手法の探求と「土」の深掘り",
    titleEn: "Research Methods & Diving into Soil",
    summary:
      "「リサーチ・スルー・デザイン」と「ブリコラージュ」的アプローチを検討。持ち寄った写真の分析を通じて、生活の中の「整然」と「雑然」からインサイトを得る試み。最終的に「土」や「土着性」をテーマにした具体的なアクションプランが設定された。",
    threads: ["rtd", "soil"],
  },
  {
    id: "2026-04-14-rtd",
    date: "2026-04-14",
    dateLabel: { y: "2026", m: "04", d: "14" },
    month: "April",
    category: "concept",
    categoryLabel: "コンセプト",
    categoryEn: "Concept",
    title: "リサーチ・スルー・デザイン",
    titleEn: "Research Through Design",
    summary:
      "作ることを通じてリサーチを進める手法。単なる最終成果物のための前段階ではなく、制作プロセス自体が思考を深めるリサーチ活動となる。手を動かしながら考える。",
    threads: ["rtd", "method"],
  },
  {
    id: "2026-04-14-micro",
    date: "2026-04-14",
    dateLabel: { y: "2026", m: "04", d: "14" },
    month: "April",
    category: "concept",
    categoryLabel: "コンセプト",
    categoryEn: "Concept",
    title: "マイクロクリエーション（微創造）",
    titleEn: "Micro-creation",
    summary:
      "マジックリンのノズルをヘアバンド掛けに使う──日常生活の中で本来の用途とは違う創造的な物の使い方を発見・実践することの面白さ。習作（ブリコラージュ）を2日に1例程度のペースで実践する宿題につながる。",
    threads: ["play", "rtd"],
  },
  {
    id: "2026-04-14-photos",
    date: "2026-04-14",
    dateLabel: { y: "2026", m: "04", d: "14" },
    month: "April",
    category: "fieldwork",
    categoryLabel: "フィールド",
    categoryEn: "Fieldwork",
    title: "生活の「整然」と「雑然」を読む",
    titleEn: "Reading Order and Clutter at Home",
    summary:
      "各自が撮影した自宅のキッチンや小物入れの写真をレビュー。物が整理された「整然」と、物が集積した「雑然」の二極化。特にペン立てなど「雑然」とした箇所にこそ、個人の生活の工夫や無意識の習慣が現れやすく、デザインのヒントが隠されている。",
    threads: ["method", "inventory"],
  },
  {
    id: "2026-04-14-soil",
    date: "2026-04-14",
    dateLabel: { y: "2026", m: "04", d: "14" },
    month: "April",
    category: "concept",
    categoryLabel: "コンセプト",
    categoryEn: "Concept",
    title: "中心テーマ「土」",
    titleEn: "Soil — The Central Theme",
    summary:
      "陶芸の土から、畑の土壌、泥染め、土壁、土を使った料理まで。砂と土の違い、土とガラスの境界線。甲子園の土やグアムの星の砂のように、特定の場所の土や砂がお土産として価値を持つ現象。土に付随する物語性や文化的な意味。",
    threads: ["soil"],
    quote: "土は、場所そのものを手に取れる素材になりうる。",
  },
  {
    id: "2026-04-14-fieldwork",
    date: "2026-04-14",
    dateLabel: { y: "2026", m: "04", d: "14" },
    month: "April",
    category: "fieldwork",
    categoryLabel: "フィールド",
    categoryEn: "Fieldwork",
    title: "フィールドワーク計画",
    titleEn: "Planning the Fieldwork",
    summary:
      "浜松の「しとろ焼き」陶芸体験、地域の町工場見学。テーマを深めるためのフィールドワークのアイデアが具体的に検討された。次回ミーティングで村上から具体案を提案予定。",
    threads: ["fieldwork", "soil"],
  },
  {
    id: "2026-04-14-homework",
    date: "2026-04-14",
    dateLabel: { y: "2026", m: "04", d: "14" },
    month: "April",
    category: "task",
    categoryLabel: "行動",
    categoryEn: "Action",
    title: "宿題:アイデア創出と習作",
    titleEn: "Homework: Ideation & Études",
    summary:
      "「土着性」をテーマに、キーワード発想法（例：「土」×「遠い概念」×「ソーシャルインパクト」）を各自で実践。身の回りのものを組み合わせて新しい使い方を作る、または本来の用途とは異なる使われ方をしている例を探す。2日に1例程度のペースで写真に収める。",
    threads: ["rtd", "method"],
  },
];

// Thread dictionary — for the "Thread" layout (案B)
window.NTK_THREADS = {
  unit: { label: "ユニット", en: "Unit" },
  position: { label: "ポジション", en: "Position" },
  concept: { label: "コンセプト", en: "Concept" },
  mingei: { label: "民芸・工芸", en: "Mingei" },
  hamamatsu: { label: "浜松", en: "Hamamatsu" },
  exhibit: { label: "展示", en: "Exhibit" },
  terroir: { label: "テロワール", en: "Terroir" },
  play: { label: "遊び", en: "Play" },
  soil: { label: "土", en: "Soil" },
  process: { label: "プロセス", en: "Process" },
  fieldwork: { label: "フィールドワーク", en: "Fieldwork" },
  method: { label: "手法", en: "Method" },
  rtd: { label: "Research through Design", en: "RtD" },
  inventory: { label: "インベントリ", en: "Inventory" },
};

// Category palette — used for tag filter
window.NTK_CATEGORIES = [
  { id: "all", label: "すべて", en: "All" },
  { id: "session", label: "対話", en: "Session" },
  { id: "concept", label: "コンセプト", en: "Concept" },
  { id: "research", label: "リサーチ", en: "Research" },
  { id: "fieldwork", label: "フィールド", en: "Fieldwork" },
  { id: "task", label: "行動", en: "Action" },
];
